config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  resources :legs, :users, :trips

  get 'sessions/new'
  match 'auth/:provider/callback', to: 'sessions#create', via: [:post, :get]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'login', to: 'sessions#login', as: 'login'
  get 'logout', to: 'sessions#logout', as: 'logout'
  get 'auth/google_oauth2', as: 'google_login'

  root 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/leg.rb
class Leg < ApplicationRecord
  belongs_to :users
  belongs_to :trips
  validates :origin, :destination, presence: true
end

app/models/trip.rb
class Trip < ApplicationRecord
  has_many :users, through: :trips
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :trips, through: :legs
  has_many :legs
  validates :name, :email, :uid, :community, :voucher, :vouched, presence: true
  validates :uid, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find_by(uid: session[:user_id])
  end

  helper_method :current_user, :signed_in?

  def current_user=(user)
    session[:user_id] = user.uid
  end

  def signed_in?
    !!current_user
  end

  def authenticate_user
    unless signed_in?
      redirect_to login_url, notice: "Please log in first"
    end
  end

end

app/controllers/legs_controller.rb
class LegsController < ApplicationController
  before_action :set_leg, only: [:show, :edit, :update, :destroy]  
 
  def index
    @legs = Leg.all
  end
  
  def new
    @leg = Leg.new
  end
  
  def show
  end
  
  def edit
  end
  
  def create
    @leg = Leg.new(leg_params)

    respond_to do |format|
      if @leg.save
        format.html { redirect_to @leg, notice: 'leg info was successfully created.' }
        format.json { render :show, status: :created, location: @leg }
      else
        format.html { render :new }
        format.json { render json: @leg.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /legs/1
  # PATCH/PUT /legs/1.json
  def update
    respond_to do |format|
      if @leg.update(leg_params)
        format.html { redirect_to @leg, notice: 'leg was successfully updated.' }
        format.json { render :show, status: :ok, location: @leg }
      else
        format.html { render :edit }
        format.json { render json: @legs.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /legs/1
  # DELETE /legs/1.json
  def destroy
    @leg.destroy
    respond_to do |format|
      format.html { redirect_to legs_url, notice: 'leg info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_leg
      @leg = Leg.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def leg_params
      params.require(:leg).permit(:origin, :destination)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def login
    if signed_in?
      redirect_to legs_url
  end
end

  def create
    auth_hash = request.env['omniauth.auth']
    @user = User.find_or_create_by(uid: auth_hash['uid']) do |user|
      user.email = auth_hash['info']['email']
  end
  self.current_user = @user
  redirect_to users_url
end

  def logout
    redirect_to login_url, notice: 'You have been logged out'
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  def index
    @trips = Trip.all
  end

  def new
    @trip = Trip.new
  end

  def show
    
  end

  def edit
    
  end

  def create
    @trip - Trip.new(trip_params)
  end

  def update
    @leg.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: 'trip info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
# Use callbacks to share common setup or constraints between actions.
  def set_trip
    @leg = trip.find(params[:id])
  end

# Never trust parameters from the scary internet, only allow the white list through.
  def trip_params
    params.require(:trip).permit(:name, :email)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User info was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @users.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/legs_helper.rb
module LegsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KeyTransferCoordinator</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/legs/_form.html.erb
<%= form_with(model: leg, local: true) do |form| %>
  <% if leg.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(leg.errors.count, "error") %> prohibited this error from being saved:</h2>

      <ul>
        <%leg.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :origin %>
    <%= form.text_field :origin, id: :leg_origin %>
  </div>

  <div class="field">
    <%= form.label :destination %>
    <%= form.text_field :destination, id: :leg_destination %>
  </div>

  <div class="field">
      <%= form.label :user_id %>
      <%= form.text_field :user_id, id: :user_id %>
  </div>

  <div class="field">
        <%= form.label :trip_id %>
        <%= form.text_field :trip_id, id: :trip_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/legs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Find Key Route</h1>
<%= link_to 'New Legs', legs_new_path %>
<%= link_to 'Legs Index', legs_index_path %>
<%= link_to 'New Trip', trips_new_path %>
<%= link_to 'Trip Index', trips_index_path %>
<%= link_to 'New Users', users_new_path %>
<%= link_to 'Users Index', users_index_path %>

<table>
  <thead>
    <tr>
      <th>Origin</th>
      <th>Destination</th>
      <th>User ID</th>
      <th>Trip ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<tbody>
  <% @legs.each do |leg| %>
    <tr>
      <td><%= leg.origin %></td>
      <td><%= leg.destination %></td>
      <td><%= leg.user_id %></td>
      <td><%= leg.trip_id %></td>
    </tr>
  <% end %>
</tbody>
</table>

app/views/legs/new.html.erb
<h1>New Leg</h1>

<%= render 'form', leg: @leg %>

<%= link_to 'Back', legs_url %>

app/views/trips/_form.html.erb
<%= form_with(model: trip, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this error from being saved:</h2>

      <ul>
      <%user.errors.full_messages.each do |message| %>
      <li><%= message %>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div class = "field">
    <%= form.label :title %>
    <%= form.text_field :title, id: trip_title %>
    </div>

    <dic class = "field">
    <%= form.label :leg_id %>
    <%= form.text_field :leg_id, id: trip_leg_id %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>

<% end %>

app/views/trips/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trips</h1>
<%= link_to 'New Legs', legs_new_path %>
<%= link_to 'Legs Index', legs_index_path %>
<%= link_to 'New Trip', trips_new_path %>
<%= link_to 'Trip Index', trips_index_path %>
<%= link_to 'New Users', users_new_path %>
<%= link_to 'Users Index', users_index_path %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Leg_ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trips.each do |trip| %>
    <tr>
      <td><%= trip.title %></td>
      <td><%= trip.leg_id %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/trips/new.html.erb
<h1>New Trip</h1>

<%= render 'form', trip: @trip %>

<%= link_to 'Back', trips_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user information from being saved:</h2>

      <ul>
      <%user.errors.full_messages.each do |message| %>
      <li><%= message %>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <%= form.label :name %>
  <%= form.text_field :name %>
  </div>

  <div class="field">
  <%= form.label :email %>
  <%= form.text_field :email %>
  </div>

  <div class="field">
  <%= form.label :community %>
  <%= form.text_field :community %>
  </div>

  <div class="field">
  <%= form.label :voucher %>
  <%= form.text_field :voucher %>
 </div>

  <div class="field">
  <%= form.label :vouched %>
  <%= form.radio_button :vouched, id: :user_vouched %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing Users</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<% provide(:title, 'Users') %>
<h1>Users</h1>

<%= link_to 'New Legs', legs_new_path %>
<%= link_to 'Legs Index', legs_index_path %>
<%= link_to 'New Trip', trips_new_path %>
<%= link_to 'Trip Index', trips_index_path %>
<%= link_to 'New Users', users_new_path %>
<%= link_to 'Users Index', users_index_path %>

<br><br>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Community</th>
      <th>Voucher</th>
      <th>Vouched</th>
      <th colspan="6"></th>
    </tr>
  </thead>


  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.community %></td>
        <td><%= user.voucher %></td>
        <td><%= user.vouched %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New User</h1>

<%= link_to 'New Legs', legs_new_path %>
<%= link_to 'Legs Index', legs_index_path %>
<%= link_to 'New Trip', trips_new_path %>
<%= link_to 'Trip Index', trips_index_path %>
<%= link_to 'New Users', users_new_path %>
<%= link_to 'Users Index', users_index_path %>

<br><br>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>